### ISSUE TITLE
Are you still interested in further developing this project?

### ISSUE THREAD

**Issue by mariobrostech** [SelfControlApp/selfcontrol-ios#3]
Hi,

I use SelfControl a lot over on my Mac, and I'm looking for a similar alternative on iOS. Other apps work, but they don't have the sheer simplicity and killswitch-like nature that SelfControl offers. I completely understand from your previous replies that iOS is a whole other beast to make an app that monitors connections system-wide (like SelfControl does), but I was happy to stumble across this repository while I was looking for an alternative.

It looks like there haven't been any updates to this app for several years, so I wanted to know the current state of this project and if you're still committed to further developing it down the road.

Thanks in advance for your help!

**Comment by cstigler** [comment]
Hi @mariobrostech, unfortunately this isn't currently technically possible on iOS, which is why this project has been untouched for years. The current codebase basically works (minus a lot of features / bugfixing / polish) when compiled and installed via Xcode. But Apple has decided that the relevant API isn't allowed on App Store apps. The key line on [this page](https://developer.apple.com/documentation/networkextension/content_filter_providers) is "Content filter providers are only supported on supervised iOS devices.".

I don't think it's worth the effort to make a sideloaded/jailbreak app, and I don't think the alternatives (fake VPNs, Safari content-blocking APIs) are reliable and powerful enough to make it worth building on them. I've been in contact with Apple about changing their policies to make SelfControl on iOS possible, but until then it's a no-go.
